// JsFromRoutes CacheKey 6e29793d66de761efd2ef170f432031a
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
export { default as notifications } from "./NotificationsApi";
export { default as announcements } from "./AnnouncementsApi";
