// JsFromRoutes CacheKey b9f0d57f48f69b6d57b38ed81e114662
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/announcements'),
}
