// JsFromRoutes CacheKey e084bb74610ddfb09079bd8d842f78af
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/notifications'),
}
